### ISSUE TITLE
how does it deal with colors not on a colormap

### ISSUE THREAD

**Issue by brianpenghe** [horchler/rgb2map#1]
Hi developer,
I used your rgb2map.m and it worked great, except that it converted the colors not on a RGB colormap into something else (gray to cyan).
Is there a way to keep the colors not on the colormap the same as it is?

Thanks

**Comment by horchler** [comment]
Hi Brian,

Can you provide a simple example code that shows what you're talking about so that I can try to understand and reproduce the issue? It would also be helpful to know what you're trying to accomplish with rgb2map so I can make sure it's the best tool.

In general, a colormap in Matlab defines how indexed image data is displayed. If a color is not defined for a particular index in the map then interpolation and clipping will be used to pick a way to display it. I don't fully understand your issue, but it's possible that you may need to some data to the colormap so that it gets displayed how you expect.

-- Andrew

**Comment by brianpenghe** [comment]
I used this image.
Then I typed

`RGB=imread('/Users/Brian/Pictures/Untitled.png');
imagesc(rgb2map(RGB,colormap(jet)))
colormap(redblue)`


![untitled](https://user-images.githubusercontent.com/4110443/30717851-04d4694e-9ed3-11e7-9a57-fa65b55f0bec.png)


And then the image got converted but its background was also converted.

![untitled2](https://user-images.githubusercontent.com/4110443/30718007-667cbe26-9ed3-11e7-8d5b-971c88d1df65.png)

Any ideas?

**Comment by horchler** [comment]
Okay, try this:
```
RGB=imread('/Users/Brian/Pictures/Untitled.png');
imagesc(rgb2map(RGB,[gray(16);jet])); % no need to call colormap here as next line overrides it
colormap([gray(16);redblue]);
```
The last two lines can be replaced with `imshow(rgb2map(RGB,[gray(16);jet]),[gray(16);redblue]);` to display the image at 100% rather than within a standard figure and axes. The result should look like this:
![out](https://user-images.githubusercontent.com/1258537/30721462-2f82f47c-9efa-11e7-9543-50270ff273f4.png)
What I did was add some grayscale colors to the `gray` colormap to force them to stay the same.  You can try playing with the `16` number if you like. For the most control you'll need to manually extract specific RGB triplets that you want to force (black, white, the background gray, and other grays for antialiased text).

I suggested something similar [in a comment on my StackOverflow answer](https://stackoverflow.com/questions/29990133/to-imread-parula-image-in-matlab-without-losing-resolution#comment48247667_30062029) that inspired `rgb2map` to force the inclusion of just black and white.

If you end up wanting to add a`redblue` `colorbar` to this image you'll need to do some hacking to only show the red-to-blue range. Or just add it in an image editor after the fact.

**Comment by brianpenghe** [comment]
Thank you! That really solved my problem!
